import type { ConstraintField } from './types';
import {
  DIFFICULTY_MAPPING_FIELDS,
  RELATION_MODEL_FIELDS,
  SUBJECT_WORKLOAD_FIELD,
} from './constraint-fields-difficulty';
import { GRAPH_CONTROL_FIELDS } from './constraint-fields-graph';
import {
  DAILY_WORKLOAD_PACING_FIELDS,
  DAILY_WORKLOAD_TIME_FIELDS,
  PLAN_WINDOW_FIELDS,
  PRACTICAL_FEASIBILITY_CORE_FIELDS,
  PRACTICAL_FEASIBILITY_COSTUDY_FIELDS,
} from './constraint-fields-planning';
import {
  SCHEDULING_STRATEGY_BACKGROUND_FIELDS,
  SCHEDULING_STRATEGY_CORE_FIELDS,
  SCHEDULING_STRATEGY_EXCLUSION_FIELDS,
} from './constraint-fields-scheduling';

export const CONSTRAINT_FIELDS: ConstraintField[] = [
  ...PLAN_WINDOW_FIELDS,
  ...PRACTICAL_FEASIBILITY_CORE_FIELDS,
  ...DAILY_WORKLOAD_PACING_FIELDS,
  ...SUBJECT_WORKLOAD_FIELD,
  ...DAILY_WORKLOAD_TIME_FIELDS,
  ...SCHEDULING_STRATEGY_CORE_FIELDS,
  ...RELATION_MODEL_FIELDS,
  ...DIFFICULTY_MAPPING_FIELDS,
  ...PRACTICAL_FEASIBILITY_COSTUDY_FIELDS,
  ...SCHEDULING_STRATEGY_BACKGROUND_FIELDS,
  ...GRAPH_CONTROL_FIELDS,
  ...SCHEDULING_STRATEGY_EXCLUSION_FIELDS,
];
