import type { ConstraintField } from './types';

export const SUBJECT_WORKLOAD_FIELD: ConstraintField[] = [
  {
    key: 'subjectWorkloadStrength',
    group: 'Difficulty Model',
    label: 'Subject workload emphasis',
    description:
      'How strongly inferred workload clusters adjust sparse or under-evidenced books.',
    effect: 'difficulty_model',
    kind: 'number',
    min: 0,
    max: 100,
    step: 5,
  },
];

export const RELATION_MODEL_FIELDS: ConstraintField[] = [
  {
    key: 'prereqRetention',
    group: 'Relation Model',
    label: 'Prerequisite retention',
    description: 'How much prerequisite burden carries into later books.',
    effect: 'relation_model',
    kind: 'number',
    min: 0,
    max: 1,
    step: 0.05,
  },
  {
    key: 'propLiftCap',
    group: 'Relation Model',
    label: 'Propagation lift cap',
    description: 'Maximum lift from prerequisite propagation.',
    effect: 'difficulty_model',
    kind: 'number',
    min: 0.25,
    max: 4,
    step: 0.05,
  },
  {
    key: 'propMix',
    group: 'Relation Model',
    label: 'Propagation mix',
    description: 'Blend of seed difficulty and propagated signals.',
    effect: 'difficulty_model',
    kind: 'number',
    min: 0,
    max: 1,
    step: 0.05,
  },
  {
    key: 'propBreadth',
    group: 'Relation Model',
    label: 'Breadth weight',
    description: 'Weight applied to breadth load in difficulty.',
    effect: 'difficulty_model',
    kind: 'number',
    min: 0,
    max: 1,
    step: 0.01,
  },
  {
    key: 'propNovelty',
    group: 'Relation Model',
    label: 'Novelty weight',
    description: 'Weight applied to novelty load in difficulty.',
    effect: 'difficulty_model',
    kind: 'number',
    min: 0,
    max: 1,
    step: 0.01,
  },
  {
    key: 'damp',
    group: 'Relation Model',
    label: 'Damping',
    description: 'Propagation damping factor.',
    effect: 'difficulty_model',
    kind: 'number',
    min: 0,
    max: 1,
    step: 0.05,
  },
  {
    key: 'alphaCap',
    group: 'Relation Model',
    label: 'Alpha cap',
    description: 'Maximum relative weighting in difficulty blending.',
    effect: 'difficulty_model',
    kind: 'number',
    min: 0,
    max: 1,
    step: 0.05,
  },
  {
    key: 'absFloor',
    group: 'Relation Model',
    label: 'Absolute floor',
    description: 'Minimum absolute contribution when blending difficulty.',
    effect: 'difficulty_model',
    kind: 'number',
    min: 0,
    max: 1,
    step: 0.05,
  },
  {
    key: 'blendMode',
    group: 'Relation Model',
    label: 'Blend mode',
    description: 'How seed and propagated difficulty are combined.',
    effect: 'difficulty_model',
    kind: 'select',
    options: [
      { value: 'geometric', label: 'Geometric' },
      { value: 'linear', label: 'Linear' },
    ],
  },
];

export const DIFFICULTY_MAPPING_FIELDS: ConstraintField[] = [
  {
    key: 'compressMode',
    group: 'Difficulty Mapping',
    label: 'Compression mode',
    description: 'How the score range is compressed for display.',
    effect: 'display_only',
    kind: 'select',
    options: [
      { value: 'auto', label: 'Auto' },
      { value: 'off', label: 'Off' },
      { value: 'manual', label: 'Manual' },
    ],
  },
  {
    key: 'compressCurve',
    group: 'Difficulty Mapping',
    label: 'Compression curve',
    description:
      'Shape used when compressing or spreading displayed difficulty.',
    effect: 'display_only',
    kind: 'select',
    options: [
      { value: 'power', label: 'Power' },
      { value: 'inverse_power', label: 'Inverse power' },
      { value: 'smoothstep', label: 'Smooth S-curve' },
      { value: 'inverse_smoothstep', label: 'Inverse smooth S-curve' },
      { value: 'tanh', label: 'Tanh S-curve' },
      { value: 'inverse_tanh', label: 'Inverse tanh S-curve' },
      { value: 'sine', label: 'Sine ease' },
      { value: 'inverse_sine', label: 'Inverse sine ease' },
      { value: 'logistic', label: 'Logistic S-curve' },
      { value: 'inverse_logistic', label: 'Inverse logistic S-curve' },
      { value: 'linear', label: 'Linear' },
    ],
  },
  {
    key: 'compressExp',
    group: 'Difficulty Mapping',
    label: 'Compression exponent',
    description: 'Compression intensity for displayed scores.',
    effect: 'display_only',
    kind: 'number',
    min: 0.1,
    max: 2,
    step: 0.05,
  },
  {
    key: 'diffMapMode',
    group: 'Difficulty Mapping',
    label: 'Display map mode',
    description: 'Whether displayed difficulty uses raw or scaled mapping.',
    effect: 'display_only',
    kind: 'select',
    options: [
      { value: 'raw', label: 'Raw' },
      { value: 'scaled', label: 'Scaled' },
    ],
  },
  {
    key: 'diffMapMin',
    group: 'Difficulty Mapping',
    label: 'Display min',
    description: 'Lower bound for displayed difficulty.',
    effect: 'display_only',
    kind: 'number',
    min: 1,
    max: 10,
    step: 0.1,
  },
  {
    key: 'diffMapMax',
    group: 'Difficulty Mapping',
    label: 'Display max',
    description: 'Upper bound for displayed difficulty.',
    effect: 'display_only',
    kind: 'number',
    min: 1,
    max: 10,
    step: 0.1,
  },
  {
    key: 'diffCurveFloorPoint',
    group: 'Difficulty Mapping',
    label: 'Curve floor point',
    description:
      'How long scores stay near the low end before the curve begins rising.',
    effect: 'display_only',
    kind: 'number',
    min: 0,
    max: 0.45,
    step: 0.01,
  },
  {
    key: 'diffCurveCeilingPoint',
    group: 'Difficulty Mapping',
    label: 'Curve ceiling point',
    description: 'How early scores reach the high end of the mapped range.',
    effect: 'display_only',
    kind: 'number',
    min: 0.55,
    max: 1,
    step: 0.01,
  },
  {
    key: 'diffRamp',
    group: 'Difficulty Mapping',
    label: 'Difficulty ramp',
    description: 'Additional shaping applied to display difficulty.',
    effect: 'display_only',
    kind: 'number',
    min: 0.1,
    max: 3,
    step: 0.05,
  },
];
