import type { WiringContract } from './contract-types';

export const AI_CONTRACTS: WiringContract[] = [
  {
    id: 'ai.localSettings',
    surface: 'ai',
    control: 'AI provider settings',
    command: 'updateAiLocalSettings',
    projectReads: [],
    projectWrites: [],
    uiReads: ['aiConnection'],
    uiWrites: ['aiConnection', 'aiStatus'],
    snapshotEffects: [],
    renderEffects: ['ai'],
    recomputePolicy: 'ui_only',
    testIds: [
      'tests/app/ai-recommendations.test.ts',
      'tests/app/wiring-contracts.test.ts',
    ],
    notes:
      'AI provider credentials and endpoint settings are local-only and never exported.',
  },
  {
    id: 'ai.prompt',
    surface: 'ai',
    control: 'Recommendation prompt',
    command: 'setAiRecommendationPrompt',
    projectReads: [],
    projectWrites: [],
    uiReads: ['aiPrompt'],
    uiWrites: ['aiPrompt'],
    snapshotEffects: [],
    renderEffects: ['ai'],
    recomputePolicy: 'ui_only',
    testIds: [
      'tests/app/ai-recommendations.test.ts',
      'tests/app/wiring-contracts.test.ts',
    ],
    notes:
      'Prompt text is sanitized and remains draft UI state until a request is made.',
  },
  {
    id: 'ai.request',
    surface: 'ai',
    control: 'Request AI recommendations',
    command: 'requestAiRecommendations',
    projectReads: ['PlannerProjectV1', 'EngineSnapshot'],
    projectWrites: [],
    uiReads: ['aiPrompt', 'aiConnection'],
    uiWrites: ['aiStatus', 'aiProposal'],
    snapshotEffects: [],
    renderEffects: ['ai'],
    recomputePolicy: 'async_then_snapshot',
    testIds: [
      'tests/app/ai-recommendations.test.ts',
      'tests/app/wiring-contracts.test.ts',
    ],
    notes:
      'Request builds a compact current-library/DAG context and validates provider output before display.',
  },
  {
    id: 'ai.clear',
    surface: 'ai',
    control: 'Clear AI proposal',
    command: 'clearAiRecommendation',
    projectReads: [],
    projectWrites: [],
    uiReads: ['aiProposal'],
    uiWrites: ['aiProposal', 'aiStatus'],
    snapshotEffects: [],
    renderEffects: ['ai'],
    recomputePolicy: 'ui_only',
    testIds: [
      'tests/app/ai-recommendations.test.ts',
      'tests/app/wiring-contracts.test.ts',
    ],
    notes: 'Discarding a proposal is local UI state only.',
  },
  {
    id: 'ai.apply',
    surface: 'ai',
    control: 'Apply AI proposal',
    command: 'applyAiRecommendation',
    projectReads: ['library.books', 'aiRecommendationSettings'],
    projectWrites: ['library.books'],
    uiReads: ['aiProposal'],
    uiWrites: [
      'aiProposal',
      'selectedBookId',
      'activeView',
      'banner',
      'importExportText',
    ],
    snapshotEffects: ['all'],
    renderEffects: ['all'],
    recomputePolicy: 'snapshot',
    testIds: [
      'tests/app/ai-recommendations.test.ts',
      'tests/app/wiring-contracts.test.ts',
    ],
    notes:
      'Applying a reviewed proposal is the only AI path that mutates the reading list.',
  },
];
