import type { WiringContract } from './contract-types';

export const AI_CONTRACTS: WiringContract[] = [
  {
    id: 'ai.localSettings',
    surface: 'ai',
    control: 'AI provider settings',
    command: 'updateAiLocalSettings',
    projectReads: [],
    projectWrites: [],
    uiReads: ['aiConnection'],
    uiWrites: ['aiConnection', 'aiStatus', 'aiClarificationStatus'],
    snapshotEffects: [],
    renderEffects: ['ai'],
    recomputePolicy: 'ui_only',
    testIds: [
      'tests/app/ai-recommendations.test.ts',
      'tests/app/wiring-contracts.test.ts',
    ],
    notes:
      'AI provider credentials and endpoint settings are local-only and never exported.',
  },
  {
    id: 'ai.recommendationSettings',
    surface: 'ai',
    control: 'AI recommendation settings',
    command: 'updateAiRecommendationSettings',
    projectReads: ['aiRecommendationSettings'],
    projectWrites: ['aiRecommendationSettings'],
    uiReads: [],
    uiWrites: ['aiStatus', 'aiProposal', 'aiRelationshipStatus'],
    snapshotEffects: ['all'],
    renderEffects: ['ai'],
    recomputePolicy: 'snapshot',
    testIds: [
      'tests/app/ai-recommendations.test.ts',
      'tests/app/wiring-contracts.test.ts',
    ],
    notes:
      'Recommendation count, DAG depth, and AI work mode are exported project settings.',
  },
  {
    id: 'ai.prompt',
    surface: 'ai',
    control: 'Recommendation prompt',
    command: 'setAiRecommendationPrompt',
    projectReads: [],
    projectWrites: [],
    uiReads: ['aiPrompt'],
    uiWrites: ['aiPrompt'],
    snapshotEffects: [],
    renderEffects: ['ai'],
    recomputePolicy: 'ui_only',
    testIds: [
      'tests/app/ai-recommendations.test.ts',
      'tests/app/wiring-contracts.test.ts',
    ],
    notes:
      'Prompt text is sanitized and remains draft UI state until a request is made.',
  },
  {
    id: 'ai.clarificationAnswer',
    surface: 'ai',
    control: 'AI clarification card answer',
    command: 'setAiClarificationAnswer',
    projectReads: [],
    projectWrites: [],
    uiReads: ['aiClarificationAnswers'],
    uiWrites: ['aiClarificationAnswers'],
    snapshotEffects: [],
    renderEffects: ['ai'],
    recomputePolicy: 'ui_only',
    testIds: [
      'tests/app/ai-recommendation-settings.test.ts',
      'tests/app/wiring-contracts.test.ts',
    ],
    notes:
      'Per-card clarification answers stay UI-only until the workspace generation command submits them.',
  },
  {
    id: 'ai.clarificationRequest',
    surface: 'ai',
    control: 'Ask clarifying question',
    command: 'requestAiClarification',
    projectReads: ['PlannerProjectV1', 'EngineSnapshot'],
    projectWrites: [],
    uiReads: ['aiPrompt', 'aiConnection', 'aiClarificationMessages'],
    uiWrites: [
      'aiClarificationStatus',
      'aiClarificationMessages',
      'aiClarificationAnswers',
      'aiPrompt',
    ],
    snapshotEffects: [],
    renderEffects: ['ai'],
    recomputePolicy: 'async_then_snapshot',
    testIds: [
      'tests/app/ai-recommendations.test.ts',
      'tests/app/wiring-contracts.test.ts',
    ],
    notes:
      'Clarification is a provider round trip that never mutates the project.',
  },
  {
    id: 'ai.workflowRequest',
    surface: 'ai',
    control: 'Generate AI workspace proposal',
    command: 'requestAiWorkspaceProposal',
    projectReads: ['PlannerProjectV1', 'EngineSnapshot'],
    projectWrites: [],
    uiReads: [
      'aiPrompt',
      'aiConnection',
      'aiClarificationMessages',
      'aiClarificationAnswers',
    ],
    uiWrites: [
      'aiClarificationStatus',
      'aiClarificationMessages',
      'aiClarificationAnswers',
      'aiStatus',
      'aiProposal',
      'aiRelationshipStatus',
      'aiRelationshipProposal',
    ],
    snapshotEffects: [],
    renderEffects: ['ai'],
    recomputePolicy: 'async_then_snapshot',
    testIds: [
      'tests/app/ai-recommendation-settings.test.ts',
      'tests/app/ai-relationships.test.ts',
      'tests/app/wiring-contracts.test.ts',
    ],
    notes:
      'Single AI action asks clarification cards first when needed, then runs book and/or plan generation based on AI work mode.',
  },
  {
    id: 'ai.clarificationClear',
    surface: 'ai',
    control: 'Clear clarification',
    command: 'clearAiClarification',
    projectReads: [],
    projectWrites: [],
    uiReads: ['aiClarificationMessages'],
    uiWrites: ['aiClarificationStatus', 'aiClarificationMessages'],
    snapshotEffects: [],
    renderEffects: ['ai'],
    recomputePolicy: 'ui_only',
    testIds: [
      'tests/app/ai-recommendations.test.ts',
      'tests/app/wiring-contracts.test.ts',
    ],
    notes: 'Clearing clarification transcript is local UI state only.',
  },
  {
    id: 'ai.request',
    surface: 'ai',
    control: 'Request AI recommendations',
    command: 'requestAiRecommendations',
    projectReads: ['PlannerProjectV1', 'EngineSnapshot'],
    projectWrites: [],
    uiReads: ['aiPrompt', 'aiConnection'],
    uiWrites: ['aiStatus', 'aiProposal'],
    snapshotEffects: [],
    renderEffects: ['ai'],
    recomputePolicy: 'async_then_snapshot',
    testIds: [
      'tests/app/ai-recommendations.test.ts',
      'tests/app/wiring-contracts.test.ts',
    ],
    notes:
      'Request builds a compact current-library/DAG context and validates provider output before display.',
  },
  {
    id: 'ai.clear',
    surface: 'ai',
    control: 'Clear AI proposal',
    command: 'clearAiRecommendation',
    projectReads: [],
    projectWrites: [],
    uiReads: ['aiProposal'],
    uiWrites: ['aiProposal', 'aiStatus'],
    snapshotEffects: [],
    renderEffects: ['ai'],
    recomputePolicy: 'ui_only',
    testIds: [
      'tests/app/ai-recommendations.test.ts',
      'tests/app/wiring-contracts.test.ts',
    ],
    notes: 'Discarding a proposal is local UI state only.',
  },
  {
    id: 'ai.apply',
    surface: 'ai',
    control: 'Apply AI proposal',
    command: 'applyAiRecommendation',
    projectReads: ['library.books', 'aiRecommendationSettings'],
    projectWrites: ['library.books'],
    uiReads: ['aiProposal'],
    uiWrites: [
      'aiProposal',
      'selectedBookId',
      'activeView',
      'banner',
      'importExportText',
    ],
    snapshotEffects: ['all'],
    renderEffects: ['all'],
    recomputePolicy: 'snapshot',
    testIds: [
      'tests/app/ai-recommendations.test.ts',
      'tests/app/wiring-contracts.test.ts',
    ],
    notes:
      'Applying a reviewed proposal is the only AI path that mutates the reading list.',
  },
  {
    id: 'ai.relationshipWizard',
    surface: 'ai',
    control: 'Relationship wizard',
    command: 'updateAiRelationshipWizard',
    projectReads: [],
    projectWrites: [],
    uiReads: ['aiRelationshipWizard'],
    uiWrites: [
      'aiRelationshipWizard',
      'aiRelationshipProposal',
      'aiRelationshipStatus',
    ],
    snapshotEffects: [],
    renderEffects: ['ai'],
    recomputePolicy: 'ui_only',
    testIds: [
      'tests/app/ai-recommendations.test.ts',
      'tests/app/wiring-contracts.test.ts',
    ],
    notes:
      'Relationship wizard answers stay in UI state until a provider proposal is requested.',
  },
  {
    id: 'ai.relationshipRequest',
    surface: 'ai',
    control: 'Request relationship reorganization',
    command: 'requestAiRelationshipReorganization',
    projectReads: ['PlannerProjectV1', 'EngineSnapshot'],
    projectWrites: [],
    uiReads: ['aiRelationshipWizard', 'aiConnection'],
    uiWrites: ['aiRelationshipStatus', 'aiRelationshipProposal'],
    snapshotEffects: [],
    renderEffects: ['ai'],
    recomputePolicy: 'async_then_snapshot',
    testIds: [
      'tests/app/ai-recommendations.test.ts',
      'tests/app/wiring-contracts.test.ts',
    ],
    notes:
      'Request uses the full non-secret planner context and validates only existing-book relationships.',
  },
  {
    id: 'ai.relationshipClear',
    surface: 'ai',
    control: 'Clear relationship proposal',
    command: 'clearAiRelationshipProposal',
    projectReads: [],
    projectWrites: [],
    uiReads: ['aiRelationshipProposal'],
    uiWrites: ['aiRelationshipProposal', 'aiRelationshipStatus'],
    snapshotEffects: [],
    renderEffects: ['ai'],
    recomputePolicy: 'ui_only',
    testIds: [
      'tests/app/ai-recommendations.test.ts',
      'tests/app/wiring-contracts.test.ts',
    ],
    notes: 'Discarding a relationship proposal is local UI state only.',
  },
  {
    id: 'ai.relationshipApply',
    surface: 'ai',
    control: 'Apply relationship proposal',
    command: 'applyAiRelationshipProposal',
    projectReads: ['library.books'],
    projectWrites: ['library.books'],
    uiReads: ['aiRelationshipProposal'],
    uiWrites: ['aiRelationshipProposal', 'activeView', 'banner'],
    snapshotEffects: ['all'],
    renderEffects: ['all'],
    recomputePolicy: 'snapshot',
    testIds: [
      'tests/app/ai-recommendations.test.ts',
      'tests/app/wiring-contracts.test.ts',
    ],
    notes:
      'Applying a reviewed relationship proposal mutates only plan order and manual relation fields.',
  },
];
