import type { WiringContract } from './contract-types';

export const CALENDAR_CONTRACTS: WiringContract[] = [
  {
    id: 'calendar.defer',
    surface: 'plan',
    control: 'Calendar skip/defer',
    command: 'deferCalendarEntry',
    projectReads: ['manualOverrides.deferred'],
    projectWrites: ['manualOverrides.deferred', 'manualOverrides.actuals'],
    uiReads: [],
    uiWrites: [],
    snapshotEffects: ['dayPlan', 'scheduleStats'],
    renderEffects: ['calendar', 'warnings', 'stats'],
    recomputePolicy: 'snapshot',
    testIds: ['tests/app/store.test.ts', 'tests/app/parameter-matrix.test.ts'],
    notes:
      'Deferrals are canonical manual overrides and must update the day plan.',
  },
  {
    id: 'calendar.done',
    surface: 'plan',
    control: 'Calendar done toggle',
    command: 'markCalendarEntryDone',
    projectReads: ['manualOverrides.actuals'],
    projectWrites: ['manualOverrides.actuals'],
    uiReads: [],
    uiWrites: [],
    snapshotEffects: ['dayPlan', 'scheduleStats'],
    renderEffects: ['calendar', 'warnings', 'stats'],
    recomputePolicy: 'snapshot',
    testIds: ['tests/app/store.test.ts', 'tests/app/parameter-matrix.test.ts'],
    notes: 'Actual completion status belongs to manual overrides.',
  },
  {
    id: 'calendar.minutes',
    surface: 'plan',
    control: 'Calendar actual minutes',
    command: 'setCalendarEntryMinutes',
    projectReads: ['manualOverrides.actuals'],
    projectWrites: ['manualOverrides.actuals'],
    uiReads: [],
    uiWrites: [],
    snapshotEffects: ['dayPlan', 'scheduleStats'],
    renderEffects: ['calendar', 'warnings', 'stats'],
    recomputePolicy: 'snapshot',
    testIds: ['tests/app/store.test.ts', 'tests/app/parameter-matrix.test.ts'],
    notes: 'Actual minutes alter canonical progress accounting.',
  },
  {
    id: 'calendar.pages',
    surface: 'plan',
    control: 'Calendar actual pages',
    command: 'setCalendarEntryPages',
    projectReads: ['manualOverrides.actuals'],
    projectWrites: ['manualOverrides.actuals'],
    uiReads: [],
    uiWrites: [],
    snapshotEffects: ['dayPlan', 'scheduleStats'],
    renderEffects: ['calendar', 'warnings', 'stats'],
    recomputePolicy: 'snapshot',
    testIds: ['tests/app/store.test.ts', 'tests/app/parameter-matrix.test.ts'],
    notes:
      'Actual pages alter canonical progress accounting independently of logged minutes.',
  },
  {
    id: 'calendar.clearActual',
    surface: 'plan',
    control: 'Calendar clear actual',
    command: 'clearCalendarEntryActual',
    projectReads: ['manualOverrides.actuals', 'manualOverrides.deferred'],
    projectWrites: ['manualOverrides.actuals', 'manualOverrides.deferred'],
    uiReads: [],
    uiWrites: [],
    snapshotEffects: ['dayPlan', 'scheduleStats'],
    renderEffects: ['calendar', 'warnings', 'stats'],
    recomputePolicy: 'snapshot',
    testIds: ['tests/app/store.test.ts', 'tests/app/parameter-matrix.test.ts'],
    notes: 'Clearing actuals restores the planned day allocation.',
  },
];
