import type { WiringContract } from './contract-types';

export const LIBRARY_CONTRACTS: WiringContract[] = [
  {
    id: 'library.addBook',
    surface: 'library/plan',
    control: 'Add book',
    command: 'addBook',
    projectReads: ['library.books'],
    projectWrites: ['library.books'],
    uiReads: [],
    uiWrites: ['selectedBookId', 'activeView', 'banner', 'importExportText'],
    snapshotEffects: ['topics', 'relations', 'schedulePlan', 'dayPlan'],
    renderEffects: ['library', 'gantt', 'calendar', 'graphs', 'warnings'],
    recomputePolicy: 'snapshot',
    testIds: ['tests/app/store.test.ts', 'tests/app/wiring-contracts.test.ts'],
    notes: 'Adding a draft book changes every derived planner projection.',
  },
  {
    id: 'library.addFromSuggestion',
    surface: 'library/plan',
    control: 'Search result add/select',
    command: 'addBookFromSuggestion',
    projectReads: ['library.books'],
    projectWrites: ['library.books'],
    uiReads: ['bookSearchResults'],
    uiWrites: [
      'selectedBookId',
      'activeView',
      'bookSearchQuery',
      'bookSearchStatus',
      'banner',
    ],
    snapshotEffects: ['topics', 'relations', 'schedulePlan', 'dayPlan'],
    renderEffects: ['library', 'gantt', 'calendar', 'graphs', 'warnings'],
    recomputePolicy: 'async_then_snapshot',
    testIds: ['tests/app/store.test.ts', 'tests/app/wiring-contracts.test.ts'],
    notes:
      'Catalog additions update the project immediately and may trigger enrichment afterward.',
  },
  {
    id: 'library.updateBook',
    surface: 'library',
    control: 'Book metadata fields',
    command: 'updateBook',
    projectReads: ['library.books'],
    projectWrites: ['library.books'],
    uiReads: ['selectedBookId'],
    uiWrites: ['banner'],
    snapshotEffects: [
      'topics',
      'relations',
      'difficultyModel',
      'schedulePlan',
      'dayPlan',
    ],
    renderEffects: ['library', 'plan', 'graphs', 'diagnostics'],
    recomputePolicy: 'snapshot',
    testIds: [
      'tests/app/parameter-matrix.test.ts',
      'tests/app/wiring-contracts.test.ts',
    ],
    notes: 'Book metadata is corpus and planning input.',
  },
  {
    id: 'library.relations',
    surface: 'library',
    control: 'Prerequisite and co-study selectors',
    command: 'updateBookRelations',
    projectReads: [
      'library.books.manualPrereqs',
      'library.books.manualCoStudy',
    ],
    projectWrites: [
      'library.books.manualPrereqs',
      'library.books.manualCoStudy',
    ],
    uiReads: ['selectedBookId'],
    uiWrites: ['banner'],
    snapshotEffects: [
      'relations',
      'difficultyModel',
      'schedulePlan',
      'dayPlan',
    ],
    renderEffects: ['library', 'plan', 'graphs', 'diagnostics'],
    recomputePolicy: 'snapshot',
    testIds: ['tests/app/store.test.ts', 'tests/app/parameter-matrix.test.ts'],
    notes:
      'Manual relation edits must propagate symmetrically and rebuild graph-dependent projections.',
  },
  {
    id: 'library.moveBook',
    surface: 'library',
    control: 'Move book up/down',
    command: 'moveBook',
    projectReads: ['library.books.planOrder', 'library.books.owned'],
    projectWrites: ['library.books.planOrder'],
    uiReads: ['selectedBookId'],
    uiWrites: ['selectedBookId', 'banner'],
    snapshotEffects: ['schedulePlan', 'dayPlan', 'scheduleStats'],
    renderEffects: ['library', 'plan', 'calendar', 'gantt'],
    recomputePolicy: 'snapshot',
    testIds: ['tests/app/store.test.ts', 'tests/app/parameter-matrix.test.ts'],
    notes:
      'Manual library ordering is planner input when book order policy is prefer or enforce.',
  },
  {
    id: 'library.removeBook',
    surface: 'library',
    control: 'Remove book',
    command: 'removeBook',
    projectReads: ['library.books', 'manualOverrides', 'enrichmentCache'],
    projectWrites: ['library.books', 'manualOverrides', 'enrichmentCache'],
    uiReads: ['selectedBookId'],
    uiWrites: ['selectedBookId', 'banner'],
    snapshotEffects: ['topics', 'relations', 'schedulePlan', 'dayPlan'],
    renderEffects: ['library', 'plan', 'graphs', 'diagnostics'],
    recomputePolicy: 'snapshot',
    testIds: ['tests/app/store.test.ts', 'tests/app/wiring-contracts.test.ts'],
    notes:
      'Removal must also remove stale manual override and cache references.',
  },
];
