import type { WiringContract } from './contract-types';

export const PROJECT_CONTRACTS: WiringContract[] = [
  {
    id: 'project.importText',
    surface: 'project',
    control: 'Import JSON from editor',
    command: 'importProjectText',
    projectReads: [],
    projectWrites: ['PlannerProjectV1'],
    uiReads: ['importExportText'],
    uiWrites: ['importExportText', 'importExportDirty', 'selectedBookId', 'banner'],
    snapshotEffects: ['all'],
    renderEffects: ['all'],
    recomputePolicy: 'project_load',
    testIds: ['tests/app/store.test.ts', 'tests/app/wiring-contracts.test.ts'],
    notes: 'Import replaces the canonical project and recomputes from scratch.',
  },
  {
    id: 'project.load',
    surface: 'host/project',
    control: 'Host project load',
    command: 'loadProject',
    projectReads: [],
    projectWrites: ['PlannerProjectV1'],
    uiReads: [],
    uiWrites: ['importExportText', 'importExportDirty', 'selectedBookId', 'banner'],
    snapshotEffects: ['all'],
    renderEffects: ['all'],
    recomputePolicy: 'project_load',
    testIds: ['tests/app/store.test.ts', 'tests/app/wiring-contracts.test.ts'],
    notes: 'Host-provided project load uses the same canonical normalization path.',
  },
  {
    id: 'project.reset',
    surface: 'project',
    control: 'New empty project',
    command: 'resetProject',
    projectReads: [],
    projectWrites: ['PlannerProjectV1'],
    uiReads: [],
    uiWrites: ['importExportText', 'importExportDirty', 'selectedBookId', 'activeView', 'banner'],
    snapshotEffects: ['all'],
    renderEffects: ['all'],
    recomputePolicy: 'project_load',
    testIds: ['tests/app/wiring-contracts.test.ts'],
    notes: 'Reset is a canonical project replacement.',
  },
  {
    id: 'project.editText',
    surface: 'project',
    control: 'Project JSON text area',
    command: 'setImportExportText',
    projectReads: ['PlannerProjectV1'],
    projectWrites: [],
    uiReads: ['importExportText'],
    uiWrites: ['importExportText', 'importExportDirty'],
    snapshotEffects: [],
    renderEffects: ['project editor'],
    recomputePolicy: 'ui_only',
    testIds: ['tests/app/store.test.ts', 'tests/app/wiring-contracts.test.ts'],
    notes: 'Project JSON draft is not authoritative until imported.',
  },
  {
    id: 'project.sourceSettings',
    surface: 'project',
    control: 'Source provider matrix',
    command: 'updateSourceSettings',
    projectReads: ['sourceSettings'],
    projectWrites: ['sourceSettings'],
    uiReads: [],
    uiWrites: ['banner', 'importExportText'],
    snapshotEffects: ['diagnostics'],
    renderEffects: ['project', 'diagnostics'],
    recomputePolicy: 'snapshot',
    testIds: ['tests/app/wiring-contracts.test.ts', 'tests/app/store.test.ts'],
    notes: 'Source settings are canonical project configuration and affect subsequent enrichment behavior.',
  },
  {
    id: 'project.qbittorrentQuickStart',
    surface: 'project',
    control: 'qBittorrent quick-start setup',
    command: 'prepareQbittorrentQuickStart',
    projectReads: ['sourceSettings'],
    projectWrites: ['sourceSettings'],
    uiReads: ['qbittorrentConnection'],
    uiWrites: ['qbittorrentConnection', 'qbittorrentStatus', 'banner', 'importExportText'],
    snapshotEffects: ['diagnostics'],
    renderEffects: ['project', 'diagnostics'],
    recomputePolicy: 'snapshot',
    testIds: ['tests/app/store.test.ts', 'tests/app/wiring-contracts.test.ts'],
    notes: 'Quick-start enables qBittorrent acquisition/search policy while keeping credentials local.',
  },
  {
    id: 'project.qbittorrentLocal',
    surface: 'project',
    control: 'qBittorrent local connection settings',
    command: 'updateQbittorrentLocalSettings',
    projectReads: [],
    projectWrites: [],
    uiReads: ['qbittorrentConnection'],
    uiWrites: ['qbittorrentConnection', 'qbittorrentStatus'],
    snapshotEffects: [],
    renderEffects: ['project'],
    recomputePolicy: 'ui_only',
    testIds: ['tests/app/wiring-contracts.test.ts', 'tests/app/store.test.ts'],
    notes: 'qBittorrent credentials are local-only integration settings and are never exported.',
  },
  {
    id: 'project.qbittorrentTest',
    surface: 'project',
    control: 'Test qBittorrent connection',
    command: 'testQbittorrentConnection',
    projectReads: [],
    projectWrites: [],
    uiReads: ['qbittorrentConnection'],
    uiWrites: ['qbittorrentStatus', 'banner'],
    snapshotEffects: [],
    renderEffects: ['project'],
    recomputePolicy: 'ui_only',
    testIds: ['tests/app/wiring-contracts.test.ts', 'tests/app/store.test.ts'],
    notes: 'Connection checks are local integration diagnostics only.',
  },
  {
    id: 'project.qbittorrentPlugins',
    surface: 'project',
    control: 'Refresh qBittorrent plugins',
    command: 'refreshQbittorrentPlugins',
    projectReads: [],
    projectWrites: [],
    uiReads: ['qbittorrentConnection'],
    uiWrites: ['qbittorrentStatus'],
    snapshotEffects: [],
    renderEffects: ['project'],
    recomputePolicy: 'ui_only',
    testIds: ['tests/app/wiring-contracts.test.ts', 'tests/app/store.test.ts'],
    notes: 'Plugin discovery is local integration state; plugin allow-list changes are project mutations.',
  },
  {
    id: 'project.qbittorrentPlugin',
    surface: 'project',
    control: 'qBittorrent plugin whitelist',
    command: 'setQbittorrentPluginEnabled',
    projectReads: ['sourceSettings.qbittorrent.allowedPlugins'],
    projectWrites: ['sourceSettings.qbittorrent.allowedPlugins'],
    uiReads: ['qbittorrentStatus.plugins'],
    uiWrites: ['banner', 'importExportText'],
    snapshotEffects: ['diagnostics'],
    renderEffects: ['project', 'diagnostics'],
    recomputePolicy: 'snapshot',
    testIds: ['tests/app/wiring-contracts.test.ts', 'tests/app/store.test.ts'],
    notes: 'Plugin allow-list is exported project policy, while credentials and runtime plugin cache stay local.',
  },
  {
    id: 'project.export',
    surface: 'project',
    control: 'Copy/download JSON',
    command: 'exportProject',
    projectReads: ['PlannerProjectV1'],
    projectWrites: [],
    uiReads: [],
    uiWrites: [],
    snapshotEffects: [],
    renderEffects: [],
    recomputePolicy: 'ui_only',
    testIds: ['tests/app/wiring-contracts.test.ts'],
    notes: 'Export reads canonical project state without mutation.',
  },
];
