import type { WiringContract } from './contract-types';

export const SEARCH_CONTRACTS: WiringContract[] = [
  {
    id: 'search.query',
    surface: 'library/plan',
    control: 'Book search input',
    command: 'setBookSearchQuery',
    projectReads: [],
    projectWrites: [],
    uiReads: ['bookSearchQuery'],
    uiWrites: ['bookSearchQuery', 'bookSearchStatus', 'bookSearchResults'],
    snapshotEffects: [],
    renderEffects: ['search results'],
    recomputePolicy: 'ui_only',
    testIds: ['tests/app/store.test.ts', 'tests/app/wiring-contracts.test.ts'],
    notes: 'Search query text is UI state until a suggestion is added.',
  },
  {
    id: 'search.clear',
    surface: 'library/plan',
    control: 'Book search clear',
    command: 'clearBookSearch',
    projectReads: [],
    projectWrites: [],
    uiReads: ['bookSearchQuery', 'bookSearchResults'],
    uiWrites: ['bookSearchQuery', 'bookSearchStatus', 'bookSearchResults'],
    snapshotEffects: [],
    renderEffects: ['search results'],
    recomputePolicy: 'ui_only',
    testIds: ['tests/app/store.test.ts', 'tests/app/wiring-contracts.test.ts'],
    notes: 'Clearing search never mutates planner truth.',
  },
  {
    id: 'search.catalog',
    surface: 'library/plan',
    control: 'Catalog search/load more',
    command: 'searchCatalog',
    projectReads: [],
    projectWrites: [],
    uiReads: ['bookSearchQuery', 'bookSearchOffset'],
    uiWrites: [
      'bookSearchStatus',
      'bookSearchResults',
      'bookSearchHasMore',
      'bookSearchOffset',
    ],
    snapshotEffects: [],
    renderEffects: ['search results'],
    recomputePolicy: 'ui_only',
    testIds: ['tests/app/store.test.ts', 'tests/app/wiring-contracts.test.ts'],
    notes: 'Catalog lookup is asynchronous but only writes UI results.',
  },
  {
    id: 'search.more',
    surface: 'library/plan',
    control: 'Load more search results',
    command: 'searchCatalogMore',
    projectReads: [],
    projectWrites: [],
    uiReads: ['bookSearchQuery', 'bookSearchHasMore', 'bookSearchOffset'],
    uiWrites: [
      'bookSearchStatus',
      'bookSearchResults',
      'bookSearchHasMore',
      'bookSearchOffset',
    ],
    snapshotEffects: [],
    renderEffects: ['search results'],
    recomputePolicy: 'ui_only',
    testIds: ['tests/app/store.test.ts', 'tests/app/wiring-contracts.test.ts'],
    notes: 'Pagination appends UI results without changing planner truth.',
  },
  {
    id: 'ephemeral.searchDebounce',
    surface: 'library/plan',
    control: 'Search debounce timer',
    command: 'ephemeral',
    projectReads: [],
    projectWrites: [],
    uiReads: [],
    uiWrites: [],
    snapshotEffects: [],
    renderEffects: [],
    recomputePolicy: 'ui_only',
    testIds: ['tests/app/wiring-contracts.test.ts'],
    notes:
      'Local timer state is allowed because it only delays dispatching a registered command.',
  },
];
