import type { WiringContract } from './contract-types';

export const SHELL_CONTRACTS: WiringContract[] = [
  {
    id: 'ui.activeView',
    surface: 'shell',
    control: 'Primary navigation tabs',
    command: 'setActiveView',
    projectReads: [],
    projectWrites: [],
    uiReads: ['activeView'],
    uiWrites: ['activeView'],
    snapshotEffects: [],
    renderEffects: ['active view'],
    recomputePolicy: 'ui_only',
    testIds: ['tests/app/wiring-contracts.test.ts'],
    notes: 'Navigation is display state only.',
  },
  {
    id: 'ui.selectBook',
    surface: 'library/plan/graphs',
    control: 'Book selection',
    command: 'selectBook',
    projectReads: ['library.books'],
    projectWrites: [],
    uiReads: ['selectedBookId'],
    uiWrites: ['selectedBookId'],
    snapshotEffects: [],
    renderEffects: ['book inspector', 'selected row'],
    recomputePolicy: 'ui_only',
    testIds: ['tests/app/wiring-contracts.test.ts'],
    notes: 'Selection changes visible detail panes but never planner truth.',
  },
  {
    id: 'ui.banner',
    surface: 'shell',
    control: 'Status banner',
    command: 'setBanner',
    projectReads: [],
    projectWrites: [],
    uiReads: ['banner'],
    uiWrites: ['banner'],
    snapshotEffects: [],
    renderEffects: ['banner'],
    recomputePolicy: 'ui_only',
    testIds: ['tests/app/wiring-contracts.test.ts'],
    notes: 'Banner writes are non-semantic UI feedback.',
  },
  {
    id: 'ui.graphOptionsOpen',
    surface: 'graphs',
    control: 'Graph settings disclosure',
    command: 'setGraphOptionsOpen',
    projectReads: [],
    projectWrites: [],
    uiReads: ['graphOptionsOpen'],
    uiWrites: ['graphOptionsOpen'],
    snapshotEffects: [],
    renderEffects: ['graph settings panel'],
    recomputePolicy: 'ui_only',
    testIds: ['tests/app/wiring-contracts.test.ts'],
    notes:
      'The graph settings dropdown open state is display-only and must not recompute planner truth.',
  },
  {
    id: 'ephemeral.focusRestore',
    surface: 'shell',
    control: 'Focus and scroll restoration',
    command: 'ephemeral',
    projectReads: [],
    projectWrites: [],
    uiReads: [],
    uiWrites: [],
    snapshotEffects: [],
    renderEffects: [],
    recomputePolicy: 'ui_only',
    testIds: ['tests/app/wiring-contracts.test.ts'],
    notes:
      'Local DOM restoration state is non-semantic and never feeds planner truth.',
  },
];
