import type { WiringContract } from './contract-types';

export const PLAN_DISPLAY_CONTRACTS: WiringContract[] = [
  {
    id: 'readingScope.book',
    surface: 'library',
    control: 'Per-book reading scope',
    command: 'updateBookReadingScope',
    projectReads: ['library.books.readingScope', 'readingScopeSettings'],
    projectWrites: ['library.books.readingScope'],
    uiReads: ['selectedBookId'],
    uiWrites: ['banner'],
    snapshotEffects: ['difficultyModel', 'schedulePlan', 'dayPlan'],
    renderEffects: ['library', 'plan', 'diagnostics'],
    recomputePolicy: 'snapshot',
    testIds: ['tests/core/reading-scope.test.ts'],
    notes:
      'Per-book reading scope changes derived effective pages while preserving the source TOC.',
  },
  {
    id: 'readingScope.project',
    surface: 'library/project',
    control: 'Global reading scope',
    command: 'updateReadingScopeSettings',
    projectReads: ['readingScopeSettings'],
    projectWrites: ['readingScopeSettings'],
    uiReads: [],
    uiWrites: ['banner'],
    snapshotEffects: ['difficultyModel', 'schedulePlan', 'dayPlan'],
    renderEffects: ['library', 'plan', 'diagnostics'],
    recomputePolicy: 'snapshot',
    testIds: ['tests/core/reading-scope.test.ts'],
    notes:
      'Global reading scope defaults apply only to books that inherit project scope.',
  },
  {
    id: 'autopilot.propose',
    surface: 'project/plan',
    control: 'Solve everything for me',
    command: 'solveProjectForMe',
    projectReads: ['constraints', 'readingScopeSettings', 'library.books'],
    projectWrites: [],
    uiReads: ['autopilotProposal'],
    uiWrites: ['autopilotProposal', 'banner'],
    snapshotEffects: [],
    renderEffects: ['project', 'plan'],
    recomputePolicy: 'ui_only',
    testIds: ['tests/app/autopilot.test.ts'],
    notes: 'Autopilot first creates a reviewable proposal and does not mutate planner truth.',
  },
  {
    id: 'autopilot.apply',
    surface: 'project/plan',
    control: 'Apply autopilot proposal',
    command: 'applyAutopilotProposal',
    projectReads: ['constraints', 'readingScopeSettings'],
    projectWrites: ['constraints', 'readingScopeSettings'],
    uiReads: ['autopilotProposal'],
    uiWrites: ['autopilotProposal', 'banner'],
    snapshotEffects: ['difficultyModel', 'schedulePlan', 'dayPlan'],
    renderEffects: ['project', 'plan', 'diagnostics'],
    recomputePolicy: 'snapshot',
    testIds: ['tests/app/autopilot.test.ts'],
    notes: 'Applying autopilot only writes the proposed bounded settings.',
  },
  {
    id: 'autopilot.clear',
    surface: 'project/plan',
    control: 'Dismiss autopilot proposal',
    command: 'clearAutopilotProposal',
    projectReads: [],
    projectWrites: [],
    uiReads: ['autopilotProposal'],
    uiWrites: ['autopilotProposal'],
    snapshotEffects: [],
    renderEffects: ['project', 'plan'],
    recomputePolicy: 'ui_only',
    testIds: ['tests/app/autopilot.test.ts'],
    notes: 'Dismissal only clears transient proposal UI state.',
  },
  {
    id: 'ui.ganttView',
    surface: 'plan',
    control: 'Gantt diagnostics toggle',
    command: 'setGanttView',
    projectReads: ['uiPreferences.ganttView'],
    projectWrites: ['uiPreferences.ganttView'],
    uiReads: ['ganttView'],
    uiWrites: ['ganttView'],
    snapshotEffects: [],
    renderEffects: ['gantt'],
    recomputePolicy: 'persistence_only',
    testIds: [
      'tests/app/wiring-contracts.test.ts',
      'tests/app/parameter-matrix.test.ts',
    ],
    notes: 'Persisted display preference; the solved schedule is unchanged.',
  },
  {
    id: 'ui.ganttZoom',
    surface: 'plan',
    control: 'Gantt zoom',
    command: 'setGanttZoom',
    projectReads: ['uiPreferences.ganttZoom'],
    projectWrites: ['uiPreferences.ganttZoom'],
    uiReads: ['ganttZoom'],
    uiWrites: ['ganttZoom'],
    snapshotEffects: [],
    renderEffects: ['gantt'],
    recomputePolicy: 'persistence_only',
    testIds: [
      'tests/app/wiring-contracts.test.ts',
      'tests/app/parameter-matrix.test.ts',
    ],
    notes: 'Persisted display preference; the solved schedule is unchanged.',
  },
  {
    id: 'ui.selectCalendarEntry',
    surface: 'plan',
    control: 'Calendar chip selection/log drawer',
    command: 'selectCalendarEntry',
    projectReads: ['library.books'],
    projectWrites: [],
    uiReads: ['selectedBookId', 'selectedCalendarEntry'],
    uiWrites: ['selectedBookId', 'selectedCalendarEntry'],
    snapshotEffects: [],
    renderEffects: ['book inspector', 'calendar log drawer'],
    recomputePolicy: 'ui_only',
    testIds: ['tests/app/wiring-contracts.test.ts', 'scripts/smoke.mjs'],
    notes:
      'Calendar selection is UI-only but keeps the exact date/book log drawer open across rerenders.',
  },
  {
    id: 'ui.documentOpen',
    surface: 'library',
    control: 'Open or reveal offline document',
    command: 'openBookDocument',
    projectReads: ['library.books.documents'],
    projectWrites: [],
    uiReads: ['qbittorrentConnection'],
    uiWrites: ['banner'],
    snapshotEffects: [],
    renderEffects: ['book inspector'],
    recomputePolicy: 'ui_only',
    testIds: ['tests/app/wiring-contracts.test.ts', 'tests/app/store.test.ts'],
    notes:
      'Opening a document is a local side effect through the bridge and does not change planner truth.',
  },
  {
    id: 'ui.documentReveal',
    surface: 'library',
    control: 'Reveal offline document location',
    command: 'revealBookDocument',
    projectReads: ['library.books.documents'],
    projectWrites: [],
    uiReads: ['qbittorrentConnection'],
    uiWrites: ['banner'],
    snapshotEffects: [],
    renderEffects: ['book inspector'],
    recomputePolicy: 'ui_only',
    testIds: ['tests/app/wiring-contracts.test.ts', 'tests/app/store.test.ts'],
    notes:
      'Revealing a document is a local side effect through the bridge and does not change planner truth.',
  },
  {
    id: 'document.remove',
    surface: 'library',
    control: 'Remove offline document',
    command: 'removeBookDocument',
    projectReads: ['library.books.documents'],
    projectWrites: ['library.books.documents'],
    uiReads: ['qbittorrentConnection'],
    uiWrites: ['banner'],
    snapshotEffects: ['document diagnostics'],
    renderEffects: ['book inspector'],
    recomputePolicy: 'snapshot',
    testIds: ['tests/app/wiring-contracts.test.ts', 'tests/app/store.test.ts'],
    notes:
      'Document refs are project data; optional content deletion is a local bridge/qBittorrent side effect.',
  },
  {
    id: 'document.candidates',
    surface: 'library',
    control: 'Find offline document candidates',
    command: 'refreshBookDocumentCandidates',
    projectReads: ['library.books', 'sourceSettings'],
    projectWrites: ['library.books.documentAcquisition'],
    uiReads: ['qbittorrentConnection', 'documentCandidates'],
    uiWrites: ['documentCandidates'],
    snapshotEffects: ['document diagnostics'],
    renderEffects: ['book inspector'],
    recomputePolicy: 'snapshot',
    testIds: ['tests/app/wiring-contracts.test.ts', 'tests/ui/library-view.test.ts'],
    notes:
      'Candidate browsing persists the per-book ranked queue and greylist penalties; visible loading/error state remains UI-only.',
  },
  {
    id: 'document.selectCandidate',
    surface: 'library',
    control: 'Use qBittorrent document candidate',
    command: 'selectBookDocumentCandidate',
    projectReads: ['library.books', 'sourceSettings'],
    projectWrites: ['library.books.documents'],
    uiReads: ['qbittorrentConnection', 'documentCandidates'],
    uiWrites: ['documentCandidates', 'banner'],
    snapshotEffects: ['document diagnostics'],
    renderEffects: ['book inspector'],
    recomputePolicy: 'snapshot',
    testIds: ['tests/app/wiring-contracts.test.ts', 'tests/ui/library-view.test.ts'],
    notes:
      'Candidate acquisition writes one canonical document ref after qBittorrent selects a trusted file.',
  },
  {
    id: 'document.manualSource',
    surface: 'library',
    control: 'Manual qBittorrent source',
    command: 'addBookTorrentSource',
    projectReads: ['library.books', 'sourceSettings'],
    projectWrites: ['library.books.sourcePath', 'library.books.documents'],
    uiReads: ['qbittorrentConnection', 'documentCandidates'],
    uiWrites: ['documentCandidates', 'banner'],
    snapshotEffects: ['document diagnostics'],
    renderEffects: ['book inspector'],
    recomputePolicy: 'snapshot',
    testIds: ['tests/app/wiring-contracts.test.ts', 'tests/ui/library-view.test.ts'],
    notes:
      'Manual magnet or HTTPS torrent URLs are persisted on the book source path and acquired through the same trusted file gate.',
  },
  {
    id: 'document.manualSourceInput',
    surface: 'library',
    control: 'Manual qBittorrent source input',
    command: 'setBookDocumentManualSource',
    projectReads: [],
    projectWrites: [],
    uiReads: ['documentCandidates'],
    uiWrites: ['documentCandidates'],
    snapshotEffects: [],
    renderEffects: ['book inspector'],
    recomputePolicy: 'ui_only',
    testIds: ['tests/app/wiring-contracts.test.ts', 'tests/ui/library-view.test.ts'],
    notes: 'The manual source input is transient until submitted.',
  },
  {
    id: 'ui.documentReader',
    surface: 'library',
    control: 'Read offline document',
    command: 'readBookDocument',
    projectReads: ['library.books.documents'],
    projectWrites: [],
    uiReads: ['qbittorrentConnection', 'documentReader'],
    uiWrites: ['documentReader'],
    snapshotEffects: [],
    renderEffects: ['book inspector', 'document reader'],
    recomputePolicy: 'ui_only',
    testIds: ['tests/app/wiring-contracts.test.ts', 'tests/app/store.test.ts'],
    notes:
      'Reader text is local UI state loaded from the bridge and is not persisted in the project.',
  },
  {
    id: 'ui.documentReaderClose',
    surface: 'library',
    control: 'Close document reader',
    command: 'closeBookDocumentReader',
    projectReads: [],
    projectWrites: [],
    uiReads: ['documentReader'],
    uiWrites: ['documentReader'],
    snapshotEffects: [],
    renderEffects: ['document reader'],
    recomputePolicy: 'ui_only',
    testIds: ['tests/app/wiring-contracts.test.ts', 'tests/app/store.test.ts'],
    notes: 'Closing the reader clears local UI-only reader state.',
  },
  {
    id: 'metadata.clearBook',
    surface: 'library',
    control: 'Delete book metadata',
    command: 'clearBookMetadata',
    projectReads: ['library.books', 'enrichmentCache'],
    projectWrites: [
      'library.books.enrichment',
      'library.books.documents',
      'library.books.documentAcquisition',
      'enrichmentCache',
    ],
    uiReads: ['qbittorrentConnection', 'documentCandidates'],
    uiWrites: ['documentCandidates', 'banner'],
    snapshotEffects: ['document diagnostics', 'enrichment diagnostics'],
    renderEffects: ['book inspector', 'diagnostics'],
    recomputePolicy: 'snapshot',
    testIds: ['tests/app/store.test.ts', 'tests/ui/library-view.test.ts'],
    notes:
      'Book metadata cleanup preserves user progress and manual planning state while clearing enrichment/document artifacts.',
  },
  {
    id: 'ui.planColorMode',
    surface: 'plan',
    control: 'Plan color mode',
    command: 'setPlanColorMode',
    projectReads: ['uiPreferences.planColorMode'],
    projectWrites: ['uiPreferences.planColorMode'],
    uiReads: ['planColorMode'],
    uiWrites: ['planColorMode'],
    snapshotEffects: [],
    renderEffects: ['gantt', 'calendar'],
    recomputePolicy: 'persistence_only',
    testIds: [
      'tests/app/wiring-contracts.test.ts',
      'tests/app/parameter-matrix.test.ts',
    ],
    notes:
      'Persisted display preference; Gantt and calendar colors change without recomputing solver truth.',
  },
  {
    id: 'ui.planSections',
    surface: 'plan',
    control: 'Gantt and calendar collapse toggles',
    command: 'setPlanSectionOpen',
    projectReads: ['uiPreferences.planSections'],
    projectWrites: ['uiPreferences.planSections'],
    uiReads: ['planSections'],
    uiWrites: ['planSections'],
    snapshotEffects: [],
    renderEffects: ['gantt', 'calendar'],
    recomputePolicy: 'persistence_only',
    testIds: ['tests/app/wiring-contracts.test.ts', 'tests/ui/plan-view.test.ts'],
    notes:
      'Persisted section visibility only changes which Plan panels are mounted.',
  },
  {
    id: 'ui.libraryListWidth',
    surface: 'library',
    control: 'Reading list resize handle',
    command: 'setLibraryListWidth',
    projectReads: ['uiPreferences.libraryListWidthPx'],
    projectWrites: ['uiPreferences.libraryListWidthPx'],
    uiReads: ['libraryListWidthPx'],
    uiWrites: ['libraryListWidthPx'],
    snapshotEffects: [],
    renderEffects: ['library split layout'],
    recomputePolicy: 'persistence_only',
    testIds: ['tests/app/wiring-contracts.test.ts', 'tests/ui/library-view.test.ts'],
    notes:
      'Persisted library split width is display-only and does not recompute planner truth.',
  },
  {
    id: 'ui.dismissWarningCode',
    surface: 'plan',
    control: 'Dismiss warning type',
    command: 'dismissWarningCode',
    projectReads: ['uiPreferences.dismissedWarningCodes'],
    projectWrites: ['uiPreferences.dismissedWarningCodes'],
    uiReads: [],
    uiWrites: [],
    snapshotEffects: [],
    renderEffects: ['warnings'],
    recomputePolicy: 'persistence_only',
    testIds: ['tests/app/wiring-contracts.test.ts', 'tests/ui/plan-view.test.ts'],
    notes:
      'Only non-blocking warning codes can be hidden; fail severity remains visible.',
  },
  {
    id: 'ui.restoreDismissedWarnings',
    surface: 'plan',
    control: 'Restore dismissed warnings',
    command: 'restoreDismissedWarnings',
    projectReads: ['uiPreferences.dismissedWarningCodes'],
    projectWrites: ['uiPreferences.dismissedWarningCodes'],
    uiReads: [],
    uiWrites: [],
    snapshotEffects: [],
    renderEffects: ['warnings'],
    recomputePolicy: 'persistence_only',
    testIds: ['tests/app/wiring-contracts.test.ts', 'tests/ui/plan-view.test.ts'],
    notes: 'Clears display-only warning dismissal preferences.',
  },
];
