import type { WiringContract } from './contract-types';

export const PLAN_DISPLAY_CONTRACTS: WiringContract[] = [
  {
    id: 'ui.ganttView',
    surface: 'plan',
    control: 'Gantt diagnostics toggle',
    command: 'setGanttView',
    projectReads: ['uiPreferences.ganttView'],
    projectWrites: ['uiPreferences.ganttView'],
    uiReads: ['ganttView'],
    uiWrites: ['ganttView'],
    snapshotEffects: [],
    renderEffects: ['gantt'],
    recomputePolicy: 'persistence_only',
    testIds: ['tests/app/wiring-contracts.test.ts', 'tests/app/parameter-matrix.test.ts'],
    notes: 'Persisted display preference; the solved schedule is unchanged.',
  },
  {
    id: 'ui.ganttZoom',
    surface: 'plan',
    control: 'Gantt zoom',
    command: 'setGanttZoom',
    projectReads: ['uiPreferences.ganttZoom'],
    projectWrites: ['uiPreferences.ganttZoom'],
    uiReads: ['ganttZoom'],
    uiWrites: ['ganttZoom'],
    snapshotEffects: [],
    renderEffects: ['gantt'],
    recomputePolicy: 'persistence_only',
    testIds: ['tests/app/wiring-contracts.test.ts', 'tests/app/parameter-matrix.test.ts'],
    notes: 'Persisted display preference; the solved schedule is unchanged.',
  },
  {
    id: 'ui.selectCalendarEntry',
    surface: 'plan',
    control: 'Calendar chip selection/log drawer',
    command: 'selectCalendarEntry',
    projectReads: ['library.books'],
    projectWrites: [],
    uiReads: ['selectedBookId', 'selectedCalendarEntry'],
    uiWrites: ['selectedBookId', 'selectedCalendarEntry'],
    snapshotEffects: [],
    renderEffects: ['book inspector', 'calendar log drawer'],
    recomputePolicy: 'ui_only',
    testIds: ['tests/app/wiring-contracts.test.ts', 'scripts/smoke.mjs'],
    notes: 'Calendar selection is UI-only but keeps the exact date/book log drawer open across rerenders.',
  },
  {
    id: 'ui.documentOpen',
    surface: 'library',
    control: 'Open offline document',
    command: 'openBookDocument',
    projectReads: ['library.books.documents'],
    projectWrites: [],
    uiReads: ['qbittorrentConnection'],
    uiWrites: ['banner'],
    snapshotEffects: [],
    renderEffects: ['book inspector'],
    recomputePolicy: 'ui_only',
    testIds: ['tests/app/wiring-contracts.test.ts', 'tests/app/store.test.ts'],
    notes: 'Opening a document is a local side effect through the bridge and does not change planner truth.',
  },
  {
    id: 'ui.documentReader',
    surface: 'library',
    control: 'Read offline document',
    command: 'readBookDocument',
    projectReads: ['library.books.documents'],
    projectWrites: [],
    uiReads: ['qbittorrentConnection', 'documentReader'],
    uiWrites: ['documentReader'],
    snapshotEffects: [],
    renderEffects: ['book inspector', 'document reader'],
    recomputePolicy: 'ui_only',
    testIds: ['tests/app/wiring-contracts.test.ts', 'tests/app/store.test.ts'],
    notes: 'Reader text is local UI state loaded from the bridge and is not persisted in the project.',
  },
  {
    id: 'ui.documentReaderClose',
    surface: 'library',
    control: 'Close document reader',
    command: 'closeBookDocumentReader',
    projectReads: [],
    projectWrites: [],
    uiReads: ['documentReader'],
    uiWrites: ['documentReader'],
    snapshotEffects: [],
    renderEffects: ['document reader'],
    recomputePolicy: 'ui_only',
    testIds: ['tests/app/wiring-contracts.test.ts', 'tests/app/store.test.ts'],
    notes: 'Closing the reader clears local UI-only reader state.',
  },
  {
    id: 'ui.planColorMode',
    surface: 'plan',
    control: 'Plan color mode',
    command: 'setPlanColorMode',
    projectReads: ['uiPreferences.planColorMode'],
    projectWrites: ['uiPreferences.planColorMode'],
    uiReads: ['planColorMode'],
    uiWrites: ['planColorMode'],
    snapshotEffects: [],
    renderEffects: ['gantt', 'calendar'],
    recomputePolicy: 'persistence_only',
    testIds: ['tests/app/wiring-contracts.test.ts', 'tests/app/parameter-matrix.test.ts'],
    notes: 'Persisted display preference; Gantt and calendar colors change without recomputing solver truth.',
  },
];
