import type { WiringContract } from './contract-types';

export const PLAN_DISPLAY_CONTRACTS: WiringContract[] = [
  {
    id: 'ui.ganttView',
    surface: 'plan',
    control: 'Gantt diagnostics toggle',
    command: 'setGanttView',
    projectReads: ['uiPreferences.ganttView'],
    projectWrites: ['uiPreferences.ganttView'],
    uiReads: ['ganttView'],
    uiWrites: ['ganttView'],
    snapshotEffects: [],
    renderEffects: ['gantt'],
    recomputePolicy: 'persistence_only',
    testIds: [
      'tests/app/wiring-contracts.test.ts',
      'tests/app/parameter-matrix.test.ts',
    ],
    notes: 'Persisted display preference; the solved schedule is unchanged.',
  },
  {
    id: 'ui.ganttZoom',
    surface: 'plan',
    control: 'Gantt zoom',
    command: 'setGanttZoom',
    projectReads: ['uiPreferences.ganttZoom'],
    projectWrites: ['uiPreferences.ganttZoom'],
    uiReads: ['ganttZoom'],
    uiWrites: ['ganttZoom'],
    snapshotEffects: [],
    renderEffects: ['gantt'],
    recomputePolicy: 'persistence_only',
    testIds: [
      'tests/app/wiring-contracts.test.ts',
      'tests/app/parameter-matrix.test.ts',
    ],
    notes: 'Persisted display preference; the solved schedule is unchanged.',
  },
  {
    id: 'ui.selectCalendarEntry',
    surface: 'plan',
    control: 'Calendar chip selection/log drawer',
    command: 'selectCalendarEntry',
    projectReads: ['library.books'],
    projectWrites: [],
    uiReads: ['selectedBookId', 'selectedCalendarEntry'],
    uiWrites: ['selectedBookId', 'selectedCalendarEntry'],
    snapshotEffects: [],
    renderEffects: ['book inspector', 'calendar log drawer'],
    recomputePolicy: 'ui_only',
    testIds: ['tests/app/wiring-contracts.test.ts', 'scripts/smoke.mjs'],
    notes:
      'Calendar selection is UI-only but keeps the exact date/book log drawer open across rerenders.',
  },
  {
    id: 'ui.documentOpen',
    surface: 'library',
    control: 'Open offline document',
    command: 'openBookDocument',
    projectReads: ['library.books.documents'],
    projectWrites: [],
    uiReads: ['qbittorrentConnection'],
    uiWrites: ['banner'],
    snapshotEffects: [],
    renderEffects: ['book inspector'],
    recomputePolicy: 'ui_only',
    testIds: ['tests/app/wiring-contracts.test.ts', 'tests/app/store.test.ts'],
    notes:
      'Opening a document is a local side effect through the bridge and does not change planner truth.',
  },
  {
    id: 'ui.documentReader',
    surface: 'library',
    control: 'Read offline document',
    command: 'readBookDocument',
    projectReads: ['library.books.documents'],
    projectWrites: [],
    uiReads: ['qbittorrentConnection', 'documentReader'],
    uiWrites: ['documentReader'],
    snapshotEffects: [],
    renderEffects: ['book inspector', 'document reader'],
    recomputePolicy: 'ui_only',
    testIds: ['tests/app/wiring-contracts.test.ts', 'tests/app/store.test.ts'],
    notes:
      'Reader text is local UI state loaded from the bridge and is not persisted in the project.',
  },
  {
    id: 'ui.documentReaderClose',
    surface: 'library',
    control: 'Close document reader',
    command: 'closeBookDocumentReader',
    projectReads: [],
    projectWrites: [],
    uiReads: ['documentReader'],
    uiWrites: ['documentReader'],
    snapshotEffects: [],
    renderEffects: ['document reader'],
    recomputePolicy: 'ui_only',
    testIds: ['tests/app/wiring-contracts.test.ts', 'tests/app/store.test.ts'],
    notes: 'Closing the reader clears local UI-only reader state.',
  },
  {
    id: 'ui.planColorMode',
    surface: 'plan',
    control: 'Plan color mode',
    command: 'setPlanColorMode',
    projectReads: ['uiPreferences.planColorMode'],
    projectWrites: ['uiPreferences.planColorMode'],
    uiReads: ['planColorMode'],
    uiWrites: ['planColorMode'],
    snapshotEffects: [],
    renderEffects: ['gantt', 'calendar'],
    recomputePolicy: 'persistence_only',
    testIds: [
      'tests/app/wiring-contracts.test.ts',
      'tests/app/parameter-matrix.test.ts',
    ],
    notes:
      'Persisted display preference; Gantt and calendar colors change without recomputing solver truth.',
  },
  {
    id: 'ui.planSections',
    surface: 'plan',
    control: 'Gantt and calendar collapse toggles',
    command: 'setPlanSectionOpen',
    projectReads: ['uiPreferences.planSections'],
    projectWrites: ['uiPreferences.planSections'],
    uiReads: ['planSections'],
    uiWrites: ['planSections'],
    snapshotEffects: [],
    renderEffects: ['gantt', 'calendar'],
    recomputePolicy: 'persistence_only',
    testIds: ['tests/app/wiring-contracts.test.ts', 'tests/ui/plan-view.test.ts'],
    notes:
      'Persisted section visibility only changes which Plan panels are mounted.',
  },
  {
    id: 'ui.libraryListWidth',
    surface: 'library',
    control: 'Reading list resize handle',
    command: 'setLibraryListWidth',
    projectReads: ['uiPreferences.libraryListWidthPx'],
    projectWrites: ['uiPreferences.libraryListWidthPx'],
    uiReads: ['libraryListWidthPx'],
    uiWrites: ['libraryListWidthPx'],
    snapshotEffects: [],
    renderEffects: ['library split layout'],
    recomputePolicy: 'persistence_only',
    testIds: ['tests/app/wiring-contracts.test.ts', 'tests/ui/library-view.test.ts'],
    notes:
      'Persisted library split width is display-only and does not recompute planner truth.',
  },
  {
    id: 'ui.dismissWarningCode',
    surface: 'plan',
    control: 'Dismiss warning type',
    command: 'dismissWarningCode',
    projectReads: ['uiPreferences.dismissedWarningCodes'],
    projectWrites: ['uiPreferences.dismissedWarningCodes'],
    uiReads: [],
    uiWrites: [],
    snapshotEffects: [],
    renderEffects: ['warnings'],
    recomputePolicy: 'persistence_only',
    testIds: ['tests/app/wiring-contracts.test.ts', 'tests/ui/plan-view.test.ts'],
    notes:
      'Only non-blocking warning codes can be hidden; fail severity remains visible.',
  },
  {
    id: 'ui.restoreDismissedWarnings',
    surface: 'plan',
    control: 'Restore dismissed warnings',
    command: 'restoreDismissedWarnings',
    projectReads: ['uiPreferences.dismissedWarningCodes'],
    projectWrites: ['uiPreferences.dismissedWarningCodes'],
    uiReads: [],
    uiWrites: [],
    snapshotEffects: [],
    renderEffects: ['warnings'],
    recomputePolicy: 'persistence_only',
    testIds: ['tests/app/wiring-contracts.test.ts', 'tests/ui/plan-view.test.ts'],
    notes: 'Clears display-only warning dismissal preferences.',
  },
];
